"""Add pricing_advice table for Stage 14

Revision ID: 1f44d27e3ab6
Revises: b8971e6ab270
Create Date: 2025-10-02 17:30:25.839798

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1f44d27e3ab6"
down_revision: Union[str, None] = "b8971e6ab270"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pricing_advice",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("d", sa.Date(), nullable=False),
        sa.Column("sku_id", sa.Integer(), nullable=False),
        sa.Column("suggested_price", sa.Float(), nullable=True),
        sa.Column("suggested_discount_pct", sa.Float(), nullable=True),
        sa.Column("expected_profit", sa.Float(), nullable=True),
        sa.Column("quality", sa.String(length=10), nullable=True),
        sa.Column("rationale_hash", sa.String(length=64), nullable=True),
        sa.Column("reason_code", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(["sku_id"], ["sku.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("d", "sku_id", name="uq_pricing_advice_d_sku"),
    )
    op.create_index(op.f("ix_pricing_advice_d"), "pricing_advice", ["d"], unique=False)
    op.create_index(op.f("ix_pricing_advice_sku_id"), "pricing_advice", ["sku_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_pricing_advice_sku_id"), table_name="pricing_advice")
    op.drop_index(op.f("ix_pricing_advice_d"), table_name="pricing_advice")
    op.drop_table("pricing_advice")
    # ### end Alembic commands ###
