"""initial schema - core tables

Revision ID: 201473760050
Revises: 
Create Date: 2025-10-02 00:30:30.125207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '201473760050'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cashflows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('d', sa.Date(), nullable=False),
    sa.Column('marketplace', sa.String(length=10), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('ref_id', sa.String(length=64), nullable=True),
    sa.Column('src_hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cash_market_day', 'cashflows', ['marketplace', 'd'], unique=False)
    op.create_index(op.f('ix_cashflows_d'), 'cashflows', ['d'], unique=False)
    op.create_index(op.f('ix_cashflows_marketplace'), 'cashflows', ['marketplace'], unique=False)
    op.create_table('commission_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('marketplace', sa.String(length=10), nullable=False),
    sa.Column('dt_from', sa.Date(), nullable=False),
    sa.Column('rule_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commission_rules_dt_from'), 'commission_rules', ['dt_from'], unique=False)
    op.create_index(op.f('ix_commission_rules_marketplace'), 'commission_rules', ['marketplace'], unique=False)
    op.create_table('sku',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('marketplace', sa.String(length=10), nullable=False),
    sa.Column('nm_id', sa.String(length=50), nullable=True),
    sa.Column('ozon_id', sa.String(length=50), nullable=True),
    sa.Column('article', sa.String(length=100), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('marketplace', 'nm_id', name='uq_sku_wb_nm_id'),
    sa.UniqueConstraint('marketplace', 'ozon_id', name='uq_sku_ozon_id')
    )
    op.create_index(op.f('ix_sku_marketplace'), 'sku', ['marketplace'], unique=False)
    op.create_table('warehouse',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('marketplace', sa.String(length=10), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('marketplace', 'code', name='uq_wh_code')
    )
    op.create_index(op.f('ix_warehouse_marketplace'), 'warehouse', ['marketplace'], unique=False)
    op.create_table('advice_supply',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('d', sa.Date(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('window_days', sa.Integer(), nullable=False),
    sa.Column('recommended_qty', sa.Integer(), nullable=False),
    sa.Column('rationale_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['sku_id'], ['sku.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('d', 'sku_id', 'warehouse_id', 'window_days', name='uq_advice_day_sku_wh_win')
    )
    op.create_index(op.f('ix_advice_supply_d'), 'advice_supply', ['d'], unique=False)
    op.create_index(op.f('ix_advice_supply_sku_id'), 'advice_supply', ['sku_id'], unique=False)
    op.create_index(op.f('ix_advice_supply_warehouse_id'), 'advice_supply', ['warehouse_id'], unique=False)
    op.create_table('cost_price_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('dt_from', sa.Date(), nullable=False),
    sa.Column('cost_price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['sku_id'], ['sku.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku_id', 'dt_from', name='uq_cost_from')
    )
    op.create_index(op.f('ix_cost_price_history_dt_from'), 'cost_price_history', ['dt_from'], unique=False)
    op.create_index(op.f('ix_cost_price_history_sku_id'), 'cost_price_history', ['sku_id'], unique=False)
    op.create_table('daily_sales',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('d', sa.Date(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('refunds_qty', sa.Integer(), nullable=False),
    sa.Column('revenue_gross', sa.Float(), nullable=False),
    sa.Column('refunds_amount', sa.Float(), nullable=False),
    sa.Column('promo_cost', sa.Float(), nullable=False),
    sa.Column('delivery_cost', sa.Float(), nullable=False),
    sa.Column('commission_amount', sa.Float(), nullable=False),
    sa.Column('channel', sa.String(length=10), nullable=True),
    sa.Column('src_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['sku_id'], ['sku.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('d', 'sku_id', 'warehouse_id', name='uq_sales_day_sku_wh')
    )
    op.create_index(op.f('ix_daily_sales_d'), 'daily_sales', ['d'], unique=False)
    op.create_index(op.f('ix_daily_sales_sku_id'), 'daily_sales', ['sku_id'], unique=False)
    op.create_index(op.f('ix_daily_sales_warehouse_id'), 'daily_sales', ['warehouse_id'], unique=False)
    op.create_index('ix_sales_sku_day', 'daily_sales', ['sku_id', 'd'], unique=False)
    op.create_table('daily_stock',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('d', sa.Date(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('on_hand', sa.Integer(), nullable=False),
    sa.Column('in_transit', sa.Integer(), nullable=False),
    sa.Column('src_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['sku_id'], ['sku.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('d', 'sku_id', 'warehouse_id', name='uq_stock_day_sku_wh')
    )
    op.create_index(op.f('ix_daily_stock_d'), 'daily_stock', ['d'], unique=False)
    op.create_index(op.f('ix_daily_stock_sku_id'), 'daily_stock', ['sku_id'], unique=False)
    op.create_index(op.f('ix_daily_stock_warehouse_id'), 'daily_stock', ['warehouse_id'], unique=False)
    op.create_index('ix_stock_sku_day', 'daily_stock', ['sku_id', 'd'], unique=False)
    op.create_table('metrics_daily',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('d', sa.Date(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('revenue_net', sa.Float(), nullable=False),
    sa.Column('cogs', sa.Float(), nullable=False),
    sa.Column('profit', sa.Float(), nullable=False),
    sa.Column('margin', sa.Float(), nullable=False),
    sa.Column('sv7', sa.Float(), nullable=False),
    sa.Column('sv14', sa.Float(), nullable=False),
    sa.Column('sv28', sa.Float(), nullable=False),
    sa.Column('stock_cover_days', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['sku_id'], ['sku.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('d', 'sku_id', name='uq_metrics_day_sku')
    )
    op.create_index(op.f('ix_metrics_daily_d'), 'metrics_daily', ['d'], unique=False)
    op.create_index(op.f('ix_metrics_daily_sku_id'), 'metrics_daily', ['sku_id'], unique=False)
    op.create_table('reviews',
    sa.Column('review_id', sa.String(length=64), nullable=False),
    sa.Column('marketplace', sa.String(length=10), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=True),
    sa.Column('created_at_utc', sa.DateTime(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('has_media', sa.Boolean(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('reply_status', sa.String(length=20), nullable=True),
    sa.Column('reply_id', sa.String(length=64), nullable=True),
    sa.Column('replied_at_utc', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sku_id'], ['sku.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_index(op.f('ix_reviews_created_at_utc'), 'reviews', ['created_at_utc'], unique=False)
    op.create_index(op.f('ix_reviews_marketplace'), 'reviews', ['marketplace'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_marketplace'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_created_at_utc'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_metrics_daily_sku_id'), table_name='metrics_daily')
    op.drop_index(op.f('ix_metrics_daily_d'), table_name='metrics_daily')
    op.drop_table('metrics_daily')
    op.drop_index('ix_stock_sku_day', table_name='daily_stock')
    op.drop_index(op.f('ix_daily_stock_warehouse_id'), table_name='daily_stock')
    op.drop_index(op.f('ix_daily_stock_sku_id'), table_name='daily_stock')
    op.drop_index(op.f('ix_daily_stock_d'), table_name='daily_stock')
    op.drop_table('daily_stock')
    op.drop_index('ix_sales_sku_day', table_name='daily_sales')
    op.drop_index(op.f('ix_daily_sales_warehouse_id'), table_name='daily_sales')
    op.drop_index(op.f('ix_daily_sales_sku_id'), table_name='daily_sales')
    op.drop_index(op.f('ix_daily_sales_d'), table_name='daily_sales')
    op.drop_table('daily_sales')
    op.drop_index(op.f('ix_cost_price_history_sku_id'), table_name='cost_price_history')
    op.drop_index(op.f('ix_cost_price_history_dt_from'), table_name='cost_price_history')
    op.drop_table('cost_price_history')
    op.drop_index(op.f('ix_advice_supply_warehouse_id'), table_name='advice_supply')
    op.drop_index(op.f('ix_advice_supply_sku_id'), table_name='advice_supply')
    op.drop_index(op.f('ix_advice_supply_d'), table_name='advice_supply')
    op.drop_table('advice_supply')
    op.drop_index(op.f('ix_warehouse_marketplace'), table_name='warehouse')
    op.drop_table('warehouse')
    op.drop_index(op.f('ix_sku_marketplace'), table_name='sku')
    op.drop_table('sku')
    op.drop_index(op.f('ix_commission_rules_marketplace'), table_name='commission_rules')
    op.drop_index(op.f('ix_commission_rules_dt_from'), table_name='commission_rules')
    op.drop_table('commission_rules')
    op.drop_index(op.f('ix_cashflows_marketplace'), table_name='cashflows')
    op.drop_index(op.f('ix_cashflows_d'), table_name='cashflows')
    op.drop_index('ix_cash_market_day', table_name='cashflows')
    op.drop_table('cashflows')
    # ### end Alembic commands ###
