"""Add reply_text to reviews and fix job_metadata

Revision ID: b8971e6ab270
Revises: 2d3b8a10c369
Create Date: 2025-10-02 13:30:48.792584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'b8971e6ab270'
down_revision: Union[str, None] = '2d3b8a10c369'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_runs', sa.Column('job_metadata', sa.JSON(), nullable=True))
    op.drop_column('job_runs', 'metadata')
    op.add_column('reviews', sa.Column('reply_text', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'reply_text')
    op.add_column('job_runs', sa.Column('metadata', sqlite.JSON(), nullable=True))
    op.drop_column('job_runs', 'job_metadata')
    # ### end Alembic commands ###
